export enum Pages {
  Welcome = 'welcome',
  Hdd = 'hdd',
  SvgDoc = 'svg-doc',
  GettingStarted = 'getting-started',
  PopupGlobalDoc = 'popup-global-doc',
  PopupConnectedDoc = 'popup-connected-doc',
  BroadcastHandlerDoc = 'broadcast-handler-doc',
  DividerDoc = 'divider-doc',
  Closeablerowdoc = 'closeable-row-doc',
  BoolToTextDoc = 'bool-to-text-doc',
  ResizerDoc = 'resizer-doc',
  AppShellDoc = 'app-shell-doc',
  StatusMarkDoc = 'status-mark-doc',
  TableViewerDefaultDoc = 'table-viewer-default-doc',
  DateFormatDoc = 'date-format-doc',
  AnimationsDoc = 'animations-doc',
  FeedbackDoc = 'feedback-doc',
  KeyboardShortcutsDoc = 'keyboard-shortcuts-doc',
  LoadingSpinnerDoc = 'loading-spinner-doc',
  Schematic = 'schematic'
}
